window.takeawayPhraseBank = {
  positive: {
    map: [
      { title: "{target} is carry territory", action: "{stats} across the map split. Keep it in the comfort pool and make opponents prove they can beat it." },
      { title: "{target} is a green-light map", action: "{stats}. Prioritize it when the lobby gives you control of the map veto or pick order." },
      { title: "{target} is doing real work", action: "{stats}. Treat it as a reliable pick rather than a neutral map." },
      { title: "{target} is where the winrate opens up", action: "{stats}. Keep this map in rotation and review what is making the defaults work." },
      { title: "{target} is a map-pool edge", action: "{stats}. Use it as a preferred pick while the gap stays this wide." },
      { title: "{target} is one to protect", action: "{stats}. Avoid banning away one of the better-performing parts of the pool." },
    ],
    agent: [
      { title: "{target} is the real main", action: "{stats} over the rest of the agent pool. Keep the reps here and be cautious about flexing away from it." },
      { title: "{target} is pulling wins above baseline", action: "{stats}. This pick deserves priority until another agent shows the same impact." },
      { title: "{target} is a comfort lock", action: "{stats}. Build more of the plan around this agent instead of treating it as interchangeable." },
      { title: "{target} is the agent with lift", action: "{stats}. Keep the role, maps, and play patterns that are making this pick convert." },
      { title: "{target} is earning the instalock", action: "{stats}. This is the agent to benchmark other picks against." },
      { title: "{target} is carrying more than vibes", action: "{stats}. The numbers support keeping this pick near the top of the pool." },
    ],
    weapon: [
      { title: "{target} rounds are paying off", action: "{stats} against {comparison}. Keep buying it when the economy supports it." },
      { title: "{target} is converting rounds", action: "{stats}. This weapon is earning its place in the buy pattern." },
      { title: "{target} is outperforming the arsenal", action: "{stats} compared with {comparison}. Lean into it instead of defaulting away." },
      { title: "{target} is a reliable closer", action: "{stats}. Keep taking the fights and ranges where this weapon is strongest." },
      { title: "{target} is getting value", action: "{stats}. The buy is justified when the round plan lets it play to its range." },
      { title: "{target} is the weapon signal", action: "{stats}. Use this as a clue for which buy patterns deserve more reps." },
    ],
    armour: [
      { title: "{target} is stabilizing rounds", action: "{stats}. The armour state is tied to better conversion, so protect this buy pattern." },
      { title: "{target} is worth the spend", action: "{stats}. When money allows it, this setup is outperforming the alternatives." },
      { title: "{target} is a winning condition", action: "{stats}. Avoid unnecessary light or no-armour rounds when this buy is available." },
      { title: "{target} is buying margin", action: "{stats}. The extra survivability appears to be turning more rounds into wins." },
      { title: "{target} is the safer setup", action: "{stats}. Keep the economy plan pointed toward this state when possible." },
      { title: "{target} is converting the investment", action: "{stats}. This armour choice is doing enough to protect as a default." },
    ],
    tradedDeath: [
      { title: "Trades are saving death rounds", action: "{stats}. Stay closer to trade range and call contact earlier so deaths become recoverable rounds." },
      { title: "Your deaths need teammates nearby", action: "{stats} when traded quickly. Path with support instead of taking isolated exits." },
      { title: "Fast trades are a real win condition", action: "{stats}. Keep fights layered so the second player can answer within the trade window." },
      { title: "Trade spacing is paying off", action: "{stats}. Preserve the spacing that turns first deaths into round wins." },
      { title: "Answered deaths are winning rounds", action: "{stats}. Keep pairing entries and exits so contact is immediately tradeable." },
      { title: "The trade window matters", action: "{stats}. Make the next review about staying close enough to punish the killer." },
    ],
    spacing: [
      { title: "{target} is healthy at-death spacing", action: "{stats}. Keep the at-death spacing pattern; this distance bucket is converting better than the alternatives." },
      { title: "{target} is helping death rounds convert", action: "{stats}. The teammate distance at death is working, so preserve this fight structure." },
      { title: "{target} is the at-death support range", action: "{stats}. This bucket suggests the player is close enough to be supported when death happens." },
      { title: "{target} is an at-death spacing strength", action: "{stats}. Treat this as the trade/support distance to replicate when taking similar fights." },
    ],
    default: [
      { title: "{target} is above baseline", action: "{stats}. Keep using this {context} pattern; it is beating {comparison}." },
      { title: "{target} is a proven edge", action: "{stats}. Treat this {context} setup as a strength against {comparison}." },
      { title: "{target} is a useful advantage", action: "{stats}. Keep it in the plan while it stays ahead of {comparison}." },
      { title: "{target} is worth repeating", action: "{stats}. This {context} pattern is outperforming the comparison group." },
    ],
  },
  negative: {
    map: [
      { title: "{target} is leaking rounds", action: "{stats}. Ban it, drill it, or enter with a tighter plan instead of treating it as neutral." },
      { title: "{target} is the danger map", action: "{stats}. This is the map most worth reviewing before the next queue block." },
      { title: "{target} needs a reset", action: "{stats}. Revisit setups, early-round routing, and side-specific defaults here." },
      { title: "{target} is dragging the pool down", action: "{stats}. Treat it as a review priority, not just a bad-luck map." },
      { title: "{target} is the veto candidate", action: "{stats}. Until the gap closes, this is the map to ban or drill first." },
      { title: "{target} is not neutral right now", action: "{stats}. Change the plan before continuing to accept it as an even map." },
    ],
    agent: [
      { title: "{target} is not matching the rest of the pool", action: "{stats}. Review whether this pick fits your current maps, role, and comfort." },
      { title: "{target} is costing conversion", action: "{stats}. Either tighten the playbook or shift reps toward stronger agents." },
      { title: "{target} is under the line", action: "{stats}. Do not autopilot this pick until the pattern improves." },
      { title: "{target} is the shaky pick", action: "{stats}. Check whether the agent is forcing fights or roles that do not fit." },
      { title: "{target} needs a smaller map pool", action: "{stats}. Restrict this pick to spots where the game plan is clearer." },
      { title: "{target} is asking for review", action: "{stats}. Compare deaths, first fights, and utility value before locking it again." },
    ],
    weapon: [
      { title: "{target} rounds are not converting", action: "{stats}. Check whether the buy timing, range, or role assignment is putting you in bad fights." },
      { title: "{target} is a shaky buy", action: "{stats}. Treat it as a review target before making it a default purchase." },
      { title: "{target} needs cleaner usage", action: "{stats}. The weapon is underperforming, so review the round types where it appears." },
      { title: "{target} is losing value", action: "{stats}. Revisit the ranges and positions where this weapon is being used." },
      { title: "{target} is not earning the slot", action: "{stats}. Consider whether another buy gives cleaner fights in the same rounds." },
      { title: "{target} is a buy-pattern warning", action: "{stats}. The issue may be when it is bought, not only how it is aimed." },
    ],
    armour: [
      { title: "{target} is a round tax", action: "{stats}. Fix the economy plan around this state; these rounds are converting worse than alternatives." },
      { title: "{target} is exposing too many rounds", action: "{stats}. Reconsider when you accept this armour state and whether the round plan protects it." },
      { title: "{target} is the fragile setup", action: "{stats}. These rounds need either safer pacing or a different buy decision." },
      { title: "{target} is where rounds get thin", action: "{stats}. Tighten the plan when this armour state appears." },
      { title: "{target} is not surviving contact", action: "{stats}. If the buy cannot change, the positioning has to." },
      { title: "{target} needs economy discipline", action: "{stats}. Review whether these rounds should be saved, upgraded, or played slower." },
    ],
    tradedDeath: [
      { title: "Untraded deaths are punishing rounds", action: "{stats}. Tighten spacing and avoid fights teammates cannot answer." },
      { title: "Death rounds need better trade structure", action: "{stats}. The fix is positioning: make first contact easier to trade." },
      { title: "Solo deaths are too expensive", action: "{stats}. Pair the fight or delay it until support is in range." },
      { title: "The trade plan is breaking", action: "{stats}. The next improvement is making deaths immediately punishable." },
    ],
    spacing: [
      { title: "{target} is bad at-death spacing", action: "{stats}. Review these deaths for isolation, late trades, or teammates being too far away when death happens." },
      { title: "{target} is an at-death support problem", action: "{stats}. This distance bucket is underperforming, so tighten the spacing before contact." },
      { title: "{target} is too costly at death", action: "{stats}. The player is not getting enough value from this spacing pattern at the moment of death." },
      { title: "{target} needs a positioning fix", action: "{stats}. Change the route, timing, or teammate spacing before taking these fights so death is easier to trade." },
    ],
    default: [
      { title: "{target} is below baseline", action: "{stats}. Review this {context} pattern; it is trailing {comparison}." },
      { title: "{target} needs attention", action: "{stats}. This {context} setup is underperforming the comparison group." },
      { title: "{target} is the weak spot", action: "{stats}. Treat this {context} pattern as a fix target against {comparison}." },
      { title: "{target} is losing the comparison", action: "{stats}. Change the plan or reduce exposure to this {context} setup." },
    ],
  },
};
